monsieurbiz_sylius_alert_message_admin:
  resource: |
    alias: monsieurbiz_alert_message.message
    section: admin
    permission: true
    templates: "@SyliusAdmin\\shared\\crud"
    except: ['show']
    redirect: update
    grid: monsieurbiz_alert_message
    vars:
        all:
            subheader: monsieurbiz_alert_message.ui.messages_subheader
        index:
            icon: 'podcast'
  type: sylius.resource
