sylius_grid:
  grids:
    monsieurbiz_alert_message:
      driver:
        name: doctrine/orm
        options:
          class: '%monsieurbiz_alert_message.model.message.class%'
      limits: [25, 50, 100, 200]
      fields:
        name:
          type: string
          label: monsieurbiz_alert_message.ui.form.name
        description:
          type: string
          label: monsieurbiz_alert_message.ui.form.description
        fromDate:
          type: datetime
          label: monsieurbiz_alert_message.ui.form.from
        toDate:
          type: datetime
          label: monsieurbiz_alert_message.ui.form.to
        enabled:
          type: twig
          label: monsieurbiz_alert_message.ui.form.enabled
          options:
            template: "@SyliusAdmin/shared/grid/field/boolean.html.twig"
        customersOnly:
          type: twig
          label: monsieurbiz_alert_message.ui.form.customers_only
          options:
            template: "@SyliusAdmin/shared/grid/field/boolean.html.twig"
      actions:
        main:
          create:
            type: create
            label: monsieurbiz_alert_message.ui.actions.create
        item:
          update:
            type: update
          delete:
            type: delete
      filters:
        name:
          type: string
          label: monsieurbiz_alert_message.ui.form.name
        description:
          type: string
          label: monsieurbiz_alert_message.ui.form.description
        enabled:
          type: boolean
          label: monsieurbiz_alert_message.ui.form.enabled
        customersOnly:
          type: boolean
          label: monsieurbiz_alert_message.ui.form.customers_only
        fromDate:
          type: date
          label: monsieurbiz_alert_message.ui.form.from
        toDate:
          type: date
          label: monsieurbiz_alert_message.ui.form.to
