services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MonsieurBiz\SyliusAlertMessagePlugin\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Form/Type}'


  # Tip for Sylius 1.3:
  MonsieurBiz\SyliusAlertMessagePlugin\Repository\MessageRepository:
    autowire: false

  # Repository for autowiring
  MonsieurBiz\SyliusAlertMessagePlugin\Repository\MessageRepositoryInterface:
    alias: MonsieurBiz\SyliusAlertMessagePlugin\Repository\MessageRepository

  # Menu item in admin panel
  MonsieurBiz\SyliusAlertMessagePlugin\Listener\AdminMenuListener:
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

  # Message Forms
  monsieurbiz_alert_message.form.type.message:
    class: MonsieurBiz\SyliusAlertMessagePlugin\Form\Type\MessageType
    tags:
      - { name: form.type }
    arguments:
      - '%monsieurbiz_alert_message.model.message.class%'

  monsieurbiz_alert_message.form.type.message_translation:
    class: MonsieurBiz\SyliusAlertMessagePlugin\Form\Type\MessageTranslationType
    tags:
      - { name: form.type }
    arguments:
      - '%monsieurbiz_alert_message.model.message_translation.class%'

  # Front
  monsieurbiz_alert_message.block_event_listener.layout.before_body:
    class: MonsieurBiz\SyliusAlertMessagePlugin\Block\BlockEventListener
    arguments:
      $template: '@@MonsieurBizSyliusAlertMessagePlugin/message.html.twig'
      $channelContext: '@sylius.context.channel.composite'
      $localeContext: '@sylius.context.locale.composite'
      $customerContext: '@sylius.context.customer'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.before_body, method: onBlockEvent }
